apiVersion: v1
kind: PersistentVolume
metadata:
  name: n8n-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/opt/n8n-data"