apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n-deployment
spec:
  template:
    spec:
      containers:
        - name: n8n
          env:
            - name: N8N_SECURE_COOKIE
              value: "false"